deploy_to_cloudflare_pages:
  stage: deploy
  image: node:22
  variables:
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID: "424d9dabd39849818d9e22366a20e4d6"
    CLOUDFLARE_PROJECT_NAME: "www-yayjaybae-com"
  script:
    - echo "Checking out code..."
    - git checkout $CI_COMMIT_REF_NAME
    - echo "Deploying to Cloudflare Pages..."
    - npx wrangler pages deploy ./src --project-name $CLOUDFLARE_PROJECT_NAME --branch $CI_COMMIT_REF_NAME
